# Generated by Django 4.1.3 on 2022-11-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensorapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readings",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="sensors",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
