# Generated by Django 4.1.3 on 2022-11-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensorapi", "0002_alter_readings_date_alter_sensors_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensors",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
