# Generated by Django 4.1.3 on 2022-11-08 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sensorapi", "0003_alter_sensors_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readings",
            name="sensor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sensor_name",
                to="sensorapi.sensors",
            ),
        ),
    ]
