# Generated by Django 4.1.3 on 2022-11-09 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sensorapi", "0004_alter_readings_sensor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readings",
            name="sensor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sensorapi.sensors"
            ),
        ),
    ]
